# Upon a push to master, this workflow will:
# -- run the linter
# -- run all tests
# -- rebuild documentation

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-mars_time:
    name: "Test mars_time on ${{ matrix.ox }} using Python ${{ matrix.python-version }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
        python-version: [3.9, "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install mars_time and testing utilities
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Test with pytest
        run: |
          python -m pytest ./mars_time
